### ISSUE TITLE
Can not open the video and style image in the example folder.

### ISSUE THREAD

**Issue by AlexCHENSiyu** [ivanstepanovftw/artistic-style-transfer-for-videos#1]
Can not open the video and style image in the example folder. It says style not match

**Comment by ivanstepanovftw** [comment]
Hello, @AlexCHENSiyu! It seems like you're encountering issues with opening video and style images in an example folder. This issue could be related to how the files are stored in the repository, likely with Git Large File Storage (LFS). Git LFS is used for managing large files separately from the main Git repository, allowing for more efficient handling of binary files such as images and videos.

To address this issue, please ensure that you have Git LFS installed on your system. If it's not installed, you can follow these steps to install Git LFS and subsequently access the files:

1. **Install Git LFS:** You can download Git LFS from the official site (https://git-lfs.github.com/) or use a package manager to install it on your system. For example, if you're using Homebrew on macOS, you can install it by running `brew install git-lfs` in your terminal.

2. **Initialize Git LFS:** After installing, you need to set up Git LFS on your machine. Open a terminal or command prompt and run `git lfs install`. This command needs to be run once per user account.

3. **Pull LFS Files:** Navigate to your local clone of the repository where you're trying to access the files. If you've already cloned the repository before installing Git LFS, you'll need to fetch the LFS files with `git lfs pull`. This command downloads the actual content of the large files that were previously placeholders in your clone.

I hope these steps help you resolve the issue with opening video and style images in your example folder. If you have any more questions or need further assistance, feel free to ask!

**Comment by AlexCHENSiyu** [comment]
Thank you for your help and sharing of the project.
